{{- if eq .Values.storage.type "azure" }}
{{- if not .Values.storage.azure.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openlake.hive.serviceName" . }}-secrets
  labels:
    {{- include "openlake.labels" . | nindent 4 }}
type: Opaque
stringData:
  azure-storage-key: {{ .Values.storage.azure.storageKey | quote }}
{{- end }}
{{- else if eq .Values.storage.type "aws" }}
{{- if not .Values.storage.aws.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openlake.hive.serviceName" . }}-secrets
  labels:
    {{- include "openlake.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws-access-key: {{ .Values.storage.aws.accessKey | quote }}
  aws-secret-key: {{ .Values.storage.aws.secretKey | quote }}
{{- end }}
{{- else if eq .Values.storage.type "gcp" }}
{{- if not .Values.storage.gcp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openlake.hive.serviceName" . }}-secrets
  labels:
    {{- include "openlake.labels" . | nindent 4 }}
type: Opaque
stringData:
  gcp-key-file: {{ .Values.storage.gcp.keyFile | quote }}
{{- end }}
{{- end }} 