apiVersion: v1
kind: Service
metadata:
  name: {{ include "openlake.serviceName" (dict "component" "hive-metastore" "context" .) }}
  labels:
    {{- include "openlake.labels" (dict "component" "hive-metastore" "context" $ "Release" .Release) | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: metastore
    protocol: TCP
    name: thrift
  selector:
    app.kubernetes.io/name: {{ include "openlake.serviceName" (dict "component" "hive-metastore" "context" .) }} 