apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openlake.labels" (dict "component" "jupyterhub" "context" .) | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openlake.labels" (dict "component" "jupyterhub" "context" .) | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openlake.labels" (dict "component" "jupyterhub" "context" .) | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: spark
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io 