apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-defaults
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openlake.labels" (dict "component" "jupyterhub" "context" .) | nindent 4 }}
data:
  spark-defaults.conf: |
    spark.master k8s://https://kubernetes.default.svc
    spark.kubernetes.namespace {{ .Release.Namespace }}
    spark.kubernetes.container.image {{ .Values.sparkImage.repository }}:{{ .Values.sparkImage.tag }}
    spark.kubernetes.authenticate.driver.serviceAccountName spark
    spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
    spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog
    spark.sql.catalogImplementation hive
    spark.hadoop.hive.metastore.uris {{ .Values.sparkImage.sparkConfig.hiveMetastoreUris }}
    spark.executor.instances {{ .Values.sparkImage.sparkConfig.sparkExecutorInstances }}
    spark.executor.memory {{ .Values.sparkImage.sparkConfig.sparkExecutorMemory }}
    spark.executor.cores {{ .Values.sparkImage.sparkConfig.sparkExecutorCores }}
    spark.driver.memory {{ .Values.sparkImage.sparkConfig.sparkDriverMemory }}
    spark.driver.cores {{ .Values.sparkImage.sparkConfig.sparkDriverCores }} 