image:
  tag: "468"
  pullPolicy: IfNotPresent

catalogs:
  lakehouse: |-
    connector.name=delta_lake
    hive.metastore.uri=thrift://hive-metastore:9083
    fs.native-azure.enabled=true
    azure.auth-type=ACCESS_KEY
    azure.access-key=###
    azure.endpoint=core.windows.net
    hive.metastore-cache-ttl=5h
    hive.metastore-refresh-interval=1m

server:
  workers: 1
  config:
    # Memory settings
    query.max-memory: "200MB"
    memory.heap-headroom-per-node: "200MB"
    task.writer-count: 1
    query.max-execution-time: "180s"
    query.low-memory-killer.enabled: true

coordinator:
  jvm:
    maxHeapSize: "2G"
    extraFlags:
      - "-XX:+UseG1GC"
      - "-XX:G1HeapRegionSize=32M"
      - "-XX:+UseGCOverheadLimit"
      - "-XX:+ExitOnOutOfMemoryError"
  resources:
    requests:
      memory: "2.5Gi"
      cpu: "1"
    limits:
      memory: "3Gi"
      cpu: "2"

worker:
  jvm:
    maxHeapSize: "2G"
    extraFlags:
      - "-XX:+UseG1GC"
      - "-XX:G1HeapRegionSize=32M"
      - "-XX:+UseGCOverheadLimit"
      - "-XX:+ExitOnOutOfMemoryError"
      - "-XX:G1HeapWastePercent=5"
      - "-XX:G1MixedGCCountTarget=4"
      - "-XX:InitiatingHeapOccupancyPercent=35"
      - "-XX:ConcGCThreads=4"
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "3Gi"
      cpu: "1"
  
  # Autoscaling configuration
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80


# Service configuration
service:
  type: ClusterIP
  annotations: {}

# Security configuration
security:
  tls:
    enabled: false
  authentication:
    enabled: false

# Add health checks
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1