apiVersion: v2
name: hive-metastore
description: Hive Metastore for Open Lake
type: application
version: 0.1.0
appVersion: "3.1.2"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common 