# Global configuration
global:
  # Cloud provider: azure, aws, gcp
  cloudProvider: azure
  
  # Storage configuration
  storage:
    account: "openlakeblobstorage"
    container: "datalake"
    warehouseDir: "warehouse"
    # The actual key will be provided at deployment time
    key: ""

# Postgres configuration
postgres:
  enabled: true
  clusterName: "openlake-postgres-cluster"
  operator:
    enabled: true
  operatorUI:
    enabled: true
  postgresql:
    teamId: "openlake"
    volume:
      size: 1Gi
    numberOfInstances: 1
    users:
      openlake:
        - superuser
        - createdb
      db_user: []
      metastore: []
      jupyterhub: []
    databases:
      metastore_db: metastore
      jupyterhub: jupyterhub
    version: "16" 